"use client";
import { useState,useTransition,useEffect,type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { Activity, Cable, FlaskConical, RefreshCw, ShieldCheck, Inbox, ChevronRight } from "lucide-react";
import type { CapiView,CapiInput } from "@/lib/meta-capi";
import { testCapiAction,retryCapiAction } from "@/actions/order-forms";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
const sections=[{id:"connection",label:"Koneksi",icon:Cable},{id:"test",label:"Uji koneksi",icon:FlaskConical},{id:"activity",label:"Aktivitas",icon:Activity}] as const;
export function CapiSettings({formId,saved,value,onChange,children,focusVersion=0}:{formId?:number;saved?:CapiView;value:CapiInput;onChange:(value:CapiInput)=>void;children?:ReactNode;focusVersion?:number}){
 const [section,setSection]=useState<string>("connection");
 const [code,setCode]=useState("");const [message,setMessage]=useState("");const [pending,startTransition]=useTransition();const [refreshing,refreshTransition]=useTransition();const router=useRouter();
 const [filter,setFilter]=useState("all");const [failed,setFailed]=useState(false);
 const format=(value:string)=>new Date(value).toLocaleString("id-ID",{timeZone:"Asia/Jakarta"})+" WIB";
 const events=(saved?.events??[]).filter(e=>filter==='all'||e.status===filter);
 useEffect(()=>{setMessage("");setFailed(false);},[saved?.version]);
 useEffect(()=>{setSection("connection");},[focusVersion]);
 const dirty=value.enabled!==(saved?.enabled??false)||value.pixelId!==(saved?.pixelId??"")||!!value.token;
 const statuses:Record<string,string>={pending:"Dalam antrean",sent:"Diterima Meta",failed:"Gagal",cancelled:"Dibatalkan"};
 const status=!saved?.enabled?"Nonaktif":saved.testSucceeded===true?"Aktif · tes berhasil":saved.testSucceeded===false?"Aktif · tes gagal":"Aktif · belum diuji";
 const statusColor=!saved?.enabled?"bg-muted text-muted-foreground":saved.testSucceeded===true?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300":saved.testSucceeded===false?"bg-destructive/10 text-destructive":"bg-amber-50 text-amber-800 dark:bg-amber-950/40 dark:text-amber-300";
 const testReason=!formId||!saved?.hasToken?"Simpan Pixel ID dan token pada langkah Simpan & pasang terlebih dahulu.":dirty?"Ada perubahan koneksi. Simpan terlebih dahulu agar tes memakai pengaturan terbaru.":"Ambil kode dari Events Manager → Test Events. Tes ini tidak menambah lead atau KPI.";
 return <section className="overflow-hidden rounded-xl border bg-card" aria-label="Meta Conversions API">
  <div className="flex flex-wrap items-center justify-between gap-3 border-b p-4 sm:px-5"><div><h3 className="font-semibold">Meta Pixel & CAPI</h3><p className="mt-1 text-xs text-muted-foreground">Koneksi browser dan server dalam satu tempat.</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusColor}`}>{status}</span></div>
  <nav aria-label="Bagian Meta CAPI" className="grid grid-cols-3 gap-1 border-b bg-muted/20 p-2">{sections.map(({id,label,icon:Icon})=><button key={id} type="button" aria-pressed={section===id} aria-controls={`capi-${id}`} onClick={()=>setSection(id)} className={`flex items-center justify-center gap-1.5 rounded-md px-2 py-2 text-xs transition-colors focus-visible:outline-2 focus-visible:outline-ring sm:text-sm ${section===id?"bg-background font-medium text-foreground shadow-sm":"text-muted-foreground hover:bg-muted"}`}><Icon className="size-4 shrink-0" aria-hidden="true" />{label}{id==='activity'&&!!saved?.counts.failed&&<span className="rounded-full bg-destructive/10 px-1.5 text-xs text-destructive">{saved.counts.failed}</span>}</button>)}</nav>
  <input type="hidden" name="capiSettings" value={JSON.stringify({enabled:value.enabled,pixelId:value.pixelId})} />
  <div id="capi-connection" hidden={section!=="connection"}><div className="grid gap-5 p-4 sm:p-5">
   <div className="flex items-center justify-between gap-4 rounded-lg border bg-muted/20 p-3"><div><p className="text-sm font-medium">Aktifkan Meta CAPI</p><p className="mt-1 text-xs text-muted-foreground">Kirim konversi dari server setelah lead tersimpan.</p></div><button type="button" role="switch" aria-label="Aktifkan Meta CAPI" aria-checked={value.enabled} onClick={()=>onChange({...value,enabled:!value.enabled})} className={`relative h-7 w-12 shrink-0 rounded-full transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring ${value.enabled?"bg-primary":"bg-muted-foreground/30"}`}><span className={`absolute left-0 top-1 size-5 rounded-full bg-white shadow-sm transition-transform ${value.enabled?"translate-x-6":"translate-x-1"}`} aria-hidden="true" /></button></div>
   <div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Pixel ID CAPI<Input inputMode="numeric" autoComplete="off" maxLength={25} placeholder="Contoh: 123456789012345" value={value.pixelId} onChange={e=>onChange({...value,pixelId:e.target.value.trim()})} /></label><label className="grid gap-2 text-sm font-medium">Access Token CAPI<Input name="capiToken" type="password" autoComplete="new-password" maxLength={4096} placeholder={saved?.hasToken?"Tersimpan · isi hanya untuk mengganti":"Tempel Access Token"} value={value.token} onChange={e=>onChange({...value,token:e.target.value.trim()})} /></label></div>
   <p className="flex items-start gap-2 text-xs leading-relaxed text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0" />Token terenkripsi. Pixel CAPI otomatis digunakan pada embed dengan ID event yang sama.</p>
   {children}
   <div className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-muted/30 px-3 py-2 text-xs"><span className="text-muted-foreground">{dirty?"Perubahan belum disimpan":"Simpan koneksi, lalu jalankan uji Meta."}</span><Button type="button" variant="ghost" size="sm" onClick={()=>setSection("test")}>Uji koneksi<ChevronRight className="size-3.5" /></Button></div>
   <details className="text-xs"><summary className="cursor-pointer font-medium">Panduan mendapatkan Pixel ID & token</summary><ol className="mt-3 list-inside list-decimal space-y-2 leading-relaxed text-muted-foreground"><li>Di Events Manager, pilih dataset/pixel → Settings → Conversions API → buat Access Token.</li><li>Isi Pixel ID dan token dataset yang sama, aktifkan CAPI, lalu simpan form pada langkah terakhir.</li><li>Salin Test Event Code dari Test Events, lalu buka bagian Uji koneksi.</li></ol><a className="mt-3 inline-block underline" href="https://developers.facebook.com/docs/marketing-api/conversions-api/" target="_blank" rel="noreferrer">Dokumentasi Meta CAPI ↗</a></details>
  </div></div>
  <div id="capi-test" hidden={section!=="test"}><div className="grid gap-4 p-4 sm:p-5"><div><h4 className="text-sm font-semibold">Pastikan Meta menerima event</h4><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{testReason}</p></div>
   <label className="grid gap-2 text-sm font-medium">Test Event Code<Input placeholder="TEST… dari Events Manager" maxLength={100} autoComplete="off" value={code} onChange={e=>setCode(e.target.value)} /></label>
   <div className="flex flex-wrap gap-2"><Button type="button" disabled={!formId||!saved?.hasToken||dirty||pending||!code.trim()} onClick={()=>startTransition(async()=>{try{const result=await testCapiAction(formId!,code.trim());setMessage(result?.error||result?.message||"");setFailed(!!result?.error);router.refresh();}catch{setMessage("Koneksi terputus. Refresh status untuk memeriksa hasil tes.");setFailed(true);}})}><FlaskConical />{pending?"Menguji…":"Kirim event uji ke Meta"}</Button><Button type="button" variant="outline" disabled={refreshing} onClick={()=>refreshTransition(()=>router.refresh())}><RefreshCw className={refreshing?"animate-spin":""} />Refresh status</Button></div>
   {saved?.testedAt&&<p className="text-xs text-muted-foreground">Tes terakhir: {format(saved.testedAt)}</p>}{saved?.testStatus&&!message&&<p role={saved.testSucceeded===false?"alert":"status"} className={`rounded-lg border p-3 text-sm ${saved.testSucceeded===false?"border-destructive/30 text-destructive":""}`}>{saved.testStatus}</p>}
   <p className="text-xs text-muted-foreground">Tes memakai pengaturan yang sudah disimpan. Periksa rincian event di Events Manager → Test Events.</p>
  </div></div>
  <div id="capi-activity" hidden={section!=="activity"}><div className="grid gap-4 p-4 sm:p-5">
   <div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-sm font-semibold">Pengiriman event</h4><Button type="button" size="sm" variant="outline" disabled={refreshing} onClick={()=>refreshTransition(()=>router.refresh())}><RefreshCw className={refreshing?"animate-spin":""} />Refresh status</Button></div>
   <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[["pending","Antrean"],["sent","Diterima Meta"],["failed","Gagal"],["cancelled","Dibatalkan"]].map(([key,label])=><div key={key} className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 text-xl font-semibold tabular-nums ${key==='failed'&&saved?.counts.failed?"text-destructive":""}`}>{saved?.counts[key]??0}</p></div>)}</div>
   {saved&&<details className="rounded-lg bg-muted/30 p-3 text-xs"><summary className="cursor-pointer font-medium">{saved.worker?.status==='healthy'?"● Layanan pengiriman berjalan":saved.worker?.status==='running'?"● Layanan sedang memproses":"○ Periksa status layanan pengiriman"}</summary><p className="mt-2 text-muted-foreground">{saved.worker?`${saved.worker.status==='error'?"Layanan mengalami gangguan. ":saved.worker.status==='stale'?"Belum ada kabar terbaru. ":""}Pembaruan: ${format(saved.worker.at)}`:"Status belum tersedia. Minta administrator memeriksa layanan CAPI jika status ini terus muncul."}</p></details>}
   <div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-sm font-medium">20 event terakhir</h4><select aria-label="Filter status CAPI" className="max-w-full rounded-md border bg-background px-2 py-1.5 text-xs" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua status</option>{Object.entries(statuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>
   {!events.length?<div className="grid justify-items-center gap-2 rounded-lg border border-dashed px-4 py-6 text-center"><Inbox className="size-6 text-muted-foreground" /><p className="text-sm font-medium">{saved?.events.length?"Tidak ada event dengan status ini":"Belum ada event"}</p><p className="max-w-sm text-xs leading-relaxed text-muted-foreground">{saved?.events.length?"Filter berlaku untuk 20 event terakhir.":"Setelah CAPI aktif, pendaftaran dengan izin pengukuran akan muncul di sini."}</p></div>:<div className="max-h-[480px] space-y-2 overflow-y-auto overscroll-contain pr-1">{events.map(e=><article key={e.eventId} className="rounded-lg border p-3 text-xs"><div className="flex flex-wrap items-center justify-between gap-2"><strong className={e.status==='failed'?"text-destructive":e.status==='sent'?"text-emerald-600":""}>{statuses[e.status]??e.status}</strong><span>{e.eventName} · {e.attempts}/8 percobaan</span></div><p className="mt-2 text-muted-foreground">{format(e.createdAt)}</p>{e.lastError&&<p className="mt-2 leading-relaxed">{e.lastError}</p>}<details className="mt-3 rounded-md bg-muted/30 p-2"><summary className="cursor-pointer font-medium">Detail event</summary><div className="mt-2 grid gap-1 break-all text-muted-foreground"><p>Event ID: {e.eventId}</p><p>Pixel: {e.pixelId}</p>{e.status==='pending'&&<p>Percobaan berikutnya: {format(e.nextAttemptAt)}</p>}{e.sentAt&&<p>Diterima: {format(e.sentAt)}</p>}{e.errorCode!==null&&<p>Kode Meta: {e.errorCode}</p>}{e.traceId&&<p>Trace ID: {e.traceId}</p>}</div></details>{e.status==='failed'&&<div className="mt-3 grid gap-2"><Button type="button" variant="outline" size="sm" className="w-fit" disabled={!e.canRetry||dirty||pending} onClick={()=>startTransition(async()=>{try{const result=await retryCapiAction(formId!,e.eventId);setMessage(result?.error||result?.message||"");setFailed(!!result?.error);router.refresh();}catch{setMessage("Koneksi terputus. Refresh status sebelum mencoba lagi.");setFailed(true);}})}>Coba ulang event</Button><p className="text-muted-foreground">{e.canRetry?"Perbaiki penyebab kegagalan terlebih dahulu.":"Menunggu jadwal, konfigurasi berubah, atau batas percobaan tercapai."}</p></div>}</article>)}</div>}
   <details className="text-xs text-muted-foreground"><summary className="cursor-pointer">Tentang status & percobaan ulang</summary><p className="mt-2 leading-relaxed">Ringkasan mencakup seluruh event form. Diterima Meta berarti API menerima event; atribusi iklan diperiksa di Events Manager. Percobaan ulang memakai ID asli, maksimal 8 kali dalam 24 jam. Mengganti token untuk Pixel yang sama mempertahankan antrean. Menonaktifkan CAPI atau mengganti Pixel membatalkan event yang belum terkirim.</p></details>
  </div></div>
  {message&&<p role={failed?"alert":"status"} className={`mx-4 mb-4 rounded-lg border p-3 text-sm ${failed?"border-destructive/30 bg-destructive/5 text-destructive":"bg-muted/30"}`}>{message}</p>}
 </section>;
}
