"use client";
import { useEffect,useState } from "react";
import { Radio,Tags,Music2,Info } from "lucide-react";
import type { CapiInput,CapiView } from "@/lib/meta-capi";
import type { FormTracking } from "@/lib/order-form-config";
import { CapiSettings } from "./capi-settings";
import { Input } from "@/components/ui/input";
export type TrackingFocus={platform:"meta"|"gtm"|"tiktok";version:number;field?:string};
export function TrackingSettings({formId,capi,capiValue,setCapiValue,tracking,setTracking,focus}:{formId?:number;capi?:CapiView;capiValue:CapiInput;setCapiValue:(v:CapiInput)=>void;tracking:FormTracking;setTracking:(v:FormTracking)=>void;focus:TrackingFocus}){
 const [platform,setPlatform]=useState<TrackingFocus['platform']>("meta");
 const [text,setText]=useState({meta:tracking.metaPixelIds.join(", "),gtm:tracking.gtmIds.join(", "),tiktok:tracking.tiktokPixelIds.join(", ")});
 useEffect(()=>{setPlatform(focus.platform);},[focus]);
 const ids=(value:string)=>value.split(/[\s,;]+/).filter(Boolean);
 const metaCount=new Set([...tracking.metaPixelIds,...(capiValue.enabled&&capiValue.pixelId?[capiValue.pixelId]:[])]).size;
 const platforms=[{id:"meta" as const,title:"Meta Ads",hint:"Pixel & CAPI",icon:Radio,count:metaCount},{id:"gtm" as const,title:"Google",hint:"Tag Manager",icon:Tags,count:tracking.gtmIds.length},{id:"tiktok" as const,title:"TikTok",hint:"Pixel",icon:Music2,count:tracking.tiktokPixelIds.length}];
 return <div className="grid min-w-0 gap-4">
  <nav aria-label="Platform tracking" className="grid grid-cols-3 gap-2">{platforms.map(({id,title,hint,icon:Icon,count})=><button key={id} type="button" aria-pressed={platform===id} aria-controls={`tracking-${id}`} onClick={()=>setPlatform(id)} className={`min-w-0 rounded-xl border p-3 text-left transition-colors focus-visible:outline-2 focus-visible:outline-ring ${platform===id?"border-primary/50 bg-primary/5 ring-1 ring-primary/20":"bg-card hover:bg-muted/30"}`}><span className="flex items-center justify-between gap-1"><Icon className="size-4 text-muted-foreground" aria-hidden="true" />{count>0&&<span className="rounded-full bg-background px-1.5 text-[10px] text-muted-foreground">{count} ID</span>}</span><span className="mt-2 block text-xs font-semibold sm:text-sm">{title}</span><span className="mt-0.5 block text-[11px] text-muted-foreground sm:text-xs">{hint}</span></button>)}</nav>
  <div id="tracking-meta" hidden={platform!=="meta"}><CapiSettings formId={formId} saved={capi} value={capiValue} onChange={setCapiValue} focusVersion={focus.version}>
   <div className="grid gap-3 border-t pt-4"><label className="grid gap-2 text-sm font-medium">Meta event<select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={tracking.metaEvent} onChange={e=>setTracking({...tracking,metaEvent:e.target.value as FormTracking['metaEvent']})}>{["Lead","CompleteRegistration","Contact","AddToWishlist"].map(event=><option key={event}>{event}</option>)}</select><span className="text-xs font-normal text-muted-foreground">Event yang sama digunakan untuk Pixel dan CAPI.</span></label>
   <details key={focus.version} open={focus.field==='metaPixelIds'?true:undefined} className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer font-medium">Pixel browser tambahan {tracking.metaPixelIds.length>0&&`(${tracking.metaPixelIds.length})`}</summary><div className="mt-3 grid gap-2"><label className="grid gap-2 text-xs">Meta Pixel IDs<Input value={text.meta} placeholder="123456789012345, 987654321098765" onChange={e=>{setText({...text,meta:e.target.value});setTracking({...tracking,metaPixelIds:ids(e.target.value)});}} /></label><p className="text-xs leading-relaxed text-muted-foreground">Untuk Pixel tanpa CAPI atau Pixel tambahan pada embed. Pixel CAPI tidak perlu diisi ulang di sini. Maksimal 5 ID, pisahkan dengan koma.</p></div></details></div>
  </CapiSettings></div>
  <div id="tracking-gtm" hidden={platform!=="gtm"}><section className="overflow-hidden rounded-xl border bg-card" aria-label="Google Tag Manager"><div className="border-b p-4"><h3 className="font-semibold">Google Tag Manager</h3><p className="mt-1 text-xs text-muted-foreground">Kelola Google Ads, Analytics, dan tag lainnya di landing page.</p></div><div className="grid gap-4 p-4"><label className="grid gap-2 text-sm font-medium">Google Tag Manager IDs<Input value={text.gtm} placeholder="GTM-XXXXXXX" onChange={e=>{setText({...text,gtm:e.target.value});setTracking({...tracking,gtmIds:ids(e.target.value.toUpperCase())});}} /></label><p className="text-xs text-muted-foreground">Maksimal 5 container ID, pisahkan dengan koma.</p><div className="rounded-lg bg-muted/30 p-3"><p className="text-xs text-muted-foreground">Custom Event untuk trigger GTM</p><code className="mt-1 block text-sm font-medium">kpiads_lead</code></div><details className="text-sm"><summary className="cursor-pointer font-medium">Panduan pemasangan GTM</summary><ol className="mt-3 list-inside list-decimal space-y-2 text-xs leading-relaxed text-muted-foreground"><li>Masukkan Container ID dari Google Tag Manager, lalu simpan form.</li><li>Pasang kode embed form di landing page.</li><li>Buat trigger Custom Event kpiads_lead untuk tag konversi Anda. Parameter tersedia: event_id dan form_id.</li><li>Uji dengan Preview GTM, lalu publish container.</li></ol><a href="https://developers.google.com/tag-platform/tag-manager/datalayer" target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs underline">Dokumentasi GTM ↗</a></details></div></section></div>
  <div id="tracking-tiktok" hidden={platform!=="tiktok"}><section className="overflow-hidden rounded-xl border bg-card" aria-label="TikTok Pixel"><div className="border-b p-4"><h3 className="font-semibold">TikTok Pixel</h3><p className="mt-1 text-xs text-muted-foreground">Ukur pendaftaran dari landing page melalui browser.</p></div><div className="grid gap-4 p-4"><label className="grid gap-2 text-sm font-medium">TikTok Pixel IDs<Input value={text.tiktok} placeholder="ID Pixel dari Events Manager" onChange={e=>{setText({...text,tiktok:e.target.value});setTracking({...tracking,tiktokPixelIds:ids(e.target.value.toUpperCase())});}} /></label><p className="text-xs text-muted-foreground">Maksimal 5 ID, pisahkan dengan koma. Event yang dikirim: Lead.</p><div className="rounded-lg bg-muted/30 p-3 text-xs leading-relaxed text-muted-foreground">Salin Pixel ID dari TikTok Events Manager, simpan form, lalu pasang kode embed di landing page Anda.</div></div></section></div>
  <p className="flex items-start gap-2 px-1 text-xs leading-relaxed text-muted-foreground"><Info className="mt-0.5 size-4 shrink-0" />Pixel dan GTM berjalan pada embed setelah lead tersimpan dan pengunjung mengizinkan pengukuran. CAPI juga mendukung form mandiri. Gunakan satu jalur pemasangan per Pixel agar event tidak tercatat ganda.</p>
 </div>;
}
