import type { kpiMetrics } from "./schema";

type MetricSeed = typeof kpiMetrics.$inferInsert;

export const DEFAULT_METRICS: MetricSeed[] = [
  // Advertiser
  { key: "ad_spend", name: "Ad Spend", role: "advertiser", unit: "currency", aggregation: "sum", higherIsBetter: false, weight: 0, defaultTarget: 45_000_000, sortOrder: 1, description: "Total ads budget spent across platforms (tracked against budget, not scored)." },
  { key: "leads", name: "Leads", role: "advertiser", unit: "number", aggregation: "sum", weight: 20, defaultTarget: 900, sortOrder: 2, description: "Leads / chats / form submissions generated by ads." },
  { key: "closing", name: "Closing", role: "advertiser", unit: "number", aggregation: "sum", weight: 25, defaultTarget: 180, sortOrder: 3, description: "Leads converted into paying customers." },
  { key: "revenue", name: "Revenue", role: "advertiser", unit: "currency", aggregation: "sum", weight: 20, defaultTarget: 225_000_000, sortOrder: 4, description: "Revenue attributed to ads." },
  { key: "roas", name: "ROAS", role: "advertiser", unit: "ratio", aggregation: "ratio", numeratorKey: "revenue", denominatorKey: "ad_spend", weight: 20, defaultTarget: 5, sortOrder: 5, description: "Return on ad spend = Revenue ÷ Ad Spend." },
  { key: "cpl", name: "Cost per Lead", role: "advertiser", unit: "currency", aggregation: "ratio", numeratorKey: "ad_spend", denominatorKey: "leads", higherIsBetter: false, weight: 15, defaultTarget: 50_000, sortOrder: 6, description: "Ad Spend ÷ Leads. Lower is better." },
  // Web Master
  { key: "landing_pages", name: "Landing Pages Delivered", role: "webmaster", unit: "number", aggregation: "sum", weight: 30, defaultTarget: 12, sortOrder: 1, description: "New or revamped landing pages shipped." },
  { key: "issues_resolved", name: "Issues Resolved", role: "webmaster", unit: "number", aggregation: "sum", weight: 25, defaultTarget: 40, sortOrder: 2, description: "Bugs, tracking and pixel issues fixed." },
  { key: "page_speed", name: "PageSpeed Score", role: "webmaster", unit: "number", aggregation: "avg", weight: 25, defaultTarget: 90, sortOrder: 3, description: "Average mobile PageSpeed score of active landing pages." },
  { key: "uptime", name: "Uptime", role: "webmaster", unit: "percent", aggregation: "avg", weight: 20, defaultTarget: 99.9, sortOrder: 4, description: "Website availability." },
  // SEO
  { key: "articles", name: "Articles Published", role: "seo", unit: "number", aggregation: "sum", weight: 25, defaultTarget: 30, sortOrder: 1, description: "SEO articles published." },
  { key: "backlinks", name: "Backlinks Built", role: "seo", unit: "number", aggregation: "sum", weight: 20, defaultTarget: 60, sortOrder: 2, description: "Quality backlinks acquired." },
  { key: "top10_keywords", name: "Keywords in Top 10", role: "seo", unit: "number", aggregation: "last", weight: 30, defaultTarget: 120, sortOrder: 3, description: "Tracked keywords currently ranking on Google page 1." },
  { key: "organic_sessions", name: "Organic Sessions", role: "seo", unit: "number", aggregation: "sum", weight: 25, defaultTarget: 45_000, sortOrder: 4, description: "Sessions from organic search (GA4)." },
  // Creative
  { key: "content_produced", name: "Konten Diproduksi", role: "creative", unit: "number", aggregation: "sum", weight: 40, defaultTarget: 60, sortOrder: 1, description: "Video / grafis iklan yang selesai dan diserahkan ke advertiser." },
  { key: "content_live", name: "Konten Tayang", role: "creative", unit: "number", aggregation: "sum", weight: 25, defaultTarget: 40, sortOrder: 2, description: "Konten yang dipakai di iklan aktif (lihat menu Creative)." },
  { key: "content_winning", name: "Konten Winning", role: "creative", unit: "number", aggregation: "sum", weight: 35, defaultTarget: 6, sortOrder: 3, description: "Konten yang ditandai Winning oleh advertiser / supervisor." },
];

// Keep demo definitions aligned with the target migration.
for (const metric of DEFAULT_METRICS) {
  if (["advertiser", "seo", "webmaster"].includes(metric.role)) metric.weight = 0;
  if (metric.key === "leads") Object.assign(metric, { name: "Jumlah Chat", weight: 40 });
  if (metric.key === "cpl") Object.assign(metric, { name: "CPR", weight: 30 });
  if (metric.key === "articles") Object.assign(metric, { defaultTarget: 1, targetMode: "daily", weight: 25, description: "Minimal 1 artikel per hari kalender." });
}
DEFAULT_METRICS.push(
  { key: "landing_page_views", name: "Landing Page Views", role: "advertiser", unit: "number", aggregation: "sum", weight: 0, sortOrder: 7 },
  { key: "cplv", name: "CPLV", role: "advertiser", unit: "currency", aggregation: "ratio", numeratorKey: "ad_spend", denominatorKey: "landing_page_views", higherIsBetter: false, weight: 30, sortOrder: 8 },
  { key: "seo_score", name: "SEO Score", role: "seo", aggregation: "avg", weight: 25, defaultTarget: 85, sortOrder: 5 },
  { key: "seo_impressions", name: "Impression Organik", role: "seo", aggregation: "sum", weight: 25, defaultTarget: 5, targetMode: "growth", sortOrder: 6 },
  { key: "seo_clicks", name: "Klik Organik", role: "seo", aggregation: "sum", weight: 25, defaultTarget: 5, targetMode: "growth", sortOrder: 7 },
  { key: "task_completion", name: "Penyelesaian Task", role: "webmaster", unit: "percent", aggregation: "last", weight: 100, defaultTarget: 100, sortOrder: 5 },
);
