/* Seeds a demo team with ~2 months of KPI history. Wipes existing data. */
process.env.TZ = process.env.APP_TIMEZONE || "Asia/Jakarta";

import bcrypt from "bcryptjs";
import { sql } from "drizzle-orm";
import { db } from "./index";
import {
  activities,
  campaigns,
  dailyReports,
  kpiEntries,
  kpiMetrics,
  kpiTargets,
  performanceAppraisals,
  tasks,
  users,
  type AdvertiserLevel,
  type Role,
} from "./schema";
import { computeAppraisal, SKILL_ASPECTS } from "../lib/appraisal";

type MetricSeed = typeof kpiMetrics.$inferInsert;

const METRICS: MetricSeed[] = [
  // Advertiser
  { key: "ad_spend", name: "Ad Spend", role: "advertiser", unit: "currency", aggregation: "sum", higherIsBetter: false, weight: 0, defaultTarget: 45_000_000, sortOrder: 1, description: "Total ads budget spent across platforms (tracked against budget, not scored)." },
  { key: "leads", name: "Leads", role: "advertiser", unit: "number", aggregation: "sum", weight: 20, defaultTarget: 900, sortOrder: 2, description: "Leads / chats / form submissions generated by ads." },
  { key: "closing", name: "Closing", role: "advertiser", unit: "number", aggregation: "sum", weight: 25, defaultTarget: 180, sortOrder: 3, description: "Leads converted into paying customers." },
  { key: "revenue", name: "Revenue", role: "advertiser", unit: "currency", aggregation: "sum", weight: 20, defaultTarget: 225_000_000, sortOrder: 4, description: "Revenue attributed to ads." },
  { key: "roas", name: "ROAS", role: "advertiser", unit: "ratio", aggregation: "ratio", numeratorKey: "revenue", denominatorKey: "ad_spend", weight: 20, defaultTarget: 5, sortOrder: 5, description: "Return on ad spend = Revenue ÷ Ad Spend." },
  { key: "cpl", name: "Cost per Lead", role: "advertiser", unit: "currency", aggregation: "ratio", numeratorKey: "ad_spend", denominatorKey: "leads", higherIsBetter: false, weight: 15, defaultTarget: 50_000, sortOrder: 6, description: "Ad Spend ÷ Leads. Lower is better." },
  // Web Master
  { key: "landing_pages", name: "Landing Pages Delivered", role: "webmaster", unit: "number", aggregation: "sum", weight: 30, defaultTarget: 12, sortOrder: 1, description: "New or revamped landing pages shipped." },
  { key: "issues_resolved", name: "Issues Resolved", role: "webmaster", unit: "number", aggregation: "sum", weight: 25, defaultTarget: 40, sortOrder: 2, description: "Bugs, tracking and pixel issues fixed." },
  { key: "page_speed", name: "PageSpeed Score", role: "webmaster", unit: "number", aggregation: "avg", weight: 25, defaultTarget: 90, sortOrder: 3, description: "Average mobile PageSpeed score of active landing pages." },
  { key: "uptime", name: "Uptime", role: "webmaster", unit: "percent", aggregation: "avg", weight: 20, defaultTarget: 99.9, sortOrder: 4, description: "Website availability." },
  // SEO
  { key: "articles", name: "Articles Published", role: "seo", unit: "number", aggregation: "sum", weight: 25, defaultTarget: 30, sortOrder: 1, description: "SEO articles published." },
  { key: "backlinks", name: "Backlinks Built", role: "seo", unit: "number", aggregation: "sum", weight: 20, defaultTarget: 60, sortOrder: 2, description: "Quality backlinks acquired." },
  { key: "top10_keywords", name: "Keywords in Top 10", role: "seo", unit: "number", aggregation: "last", weight: 30, defaultTarget: 120, sortOrder: 3, description: "Tracked keywords currently ranking on Google page 1." },
  { key: "organic_sessions", name: "Organic Sessions", role: "seo", unit: "number", aggregation: "sum", weight: 25, defaultTarget: 45_000, sortOrder: 4, description: "Sessions from organic search (GA4)." },
];

const PEOPLE: { name: string; email: string; role: Role; advertiserLevel?: AdvertiserLevel; title: string; factor: number }[] = [
  { name: "Achmad Hakim", email: "supervisor@kpi.local", role: "supervisor", title: "Performance Marketing Lead", factor: 1 },
  { name: "Rizky Pratama", email: "rizky@kpi.local", role: "advertiser", advertiserLevel: "senior", title: "Meta Ads Specialist", factor: 1.12 },
  { name: "Dewi Lestari", email: "dewi@kpi.local", role: "advertiser", advertiserLevel: "senior", title: "Google Ads Specialist", factor: 0.96 },
  { name: "Bima Saputra", email: "bima@kpi.local", role: "advertiser", title: "TikTok Ads Specialist", factor: 0.74 },
  { name: "Salsa Nabila", email: "salsa@kpi.local", role: "advertiser", title: "Marketplace Ads Specialist", factor: 0.88 },
  { name: "Fajar Nugroho", email: "fajar@kpi.local", role: "webmaster", title: "Web Master", factor: 1.05 },
  { name: "Intan Permata", email: "intan@kpi.local", role: "webmaster", title: "Web Developer", factor: 0.82 },
  { name: "Nadia Putri", email: "nadia@kpi.local", role: "seo", title: "SEO Specialist", factor: 1.08 },
  { name: "Yoga Firmansyah", email: "yoga@kpi.local", role: "seo", title: "SEO Content Specialist", factor: 0.66 },
];

// deterministic PRNG so every seed looks the same
let s = 42;
const rand = () => ((s = (s * 1664525 + 1013904223) % 4294967296) / 4294967296);
const around = (base: number, spread = 0.25) => base * (1 - spread + rand() * spread * 2);
const pick = <T,>(xs: T[]) => xs[Math.floor(rand() * xs.length)]!;

const iso = (d: Date) =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;

const SUMMARIES: Record<Exclude<Role, "supervisor">, string[]> = {
  advertiser: [
    "Scaled winning ad sets +20%, paused 3 creatives with CTR < 0.8%.",
    "Launched new retargeting audience from 30-day engagers.",
    "A/B tested 4 new hooks for the video creatives, 2 winners so far.",
    "Optimized bidding to cost cap, CPL dropped in the afternoon.",
    "Refreshed carousel creatives and updated UTM parameters.",
  ],
  webmaster: [
    "Shipped new landing page variant for the promo campaign.",
    "Fixed Meta pixel double-firing on the checkout page.",
    "Compressed hero images, mobile PageSpeed up by 6 points.",
    "Set up server-side tracking for Google Ads conversions.",
    "Updated WhatsApp CTA routing across all landing pages.",
  ],
  seo: [
    "Published 2 pillar articles and interlinked 8 older posts.",
    "Outreach to 15 niche sites, secured 3 guest post backlinks.",
    "Fixed 24 crawl errors from Search Console coverage report.",
    "Keyword research for next month's content calendar.",
    "Optimized meta titles for 10 pages ranking in positions 11–20.",
  ],
};

function dailyValues(role: Role, f: number): Record<string, number> {
  const k = around(f, 0.18);
  switch (role) {
    case "advertiser": {
      const spend = Math.round(around(1_500_000, 0.2) / 1000) * 1000;
      const leads = Math.max(0, Math.round((spend / 52_000) * k));
      const closing = Math.max(0, Math.round(leads * around(0.2, 0.3) * k));
      const revenue = Math.round((closing * around(1_250_000, 0.2)) / 1000) * 1000;
      return { ad_spend: spend, leads, closing, revenue };
    }
    case "webmaster":
      return {
        landing_pages: rand() < 0.45 * k ? 1 : 0,
        issues_resolved: Math.round(around(1.7 * k, 0.6)),
        page_speed: Math.min(100, Math.round(around(88 * Math.min(k, 1.08), 0.05))),
        uptime: Math.min(100, Number((99.5 + rand() * 0.5 * Math.min(k, 1)).toFixed(2))),
      };
    case "seo":
      return {
        articles: Math.round(around(1.25 * k, 0.6)),
        backlinks: Math.round(around(2.5 * k, 0.6)),
        top10_keywords: 0, // filled in with a rising trend below
        organic_sessions: Math.round(around(1_750 * k, 0.2)),
      };
    default:
      return {};
  }
}

async function main() {
  console.log("Resetting tables…");
  await db.execute(
    sql`truncate table activities, tasks, campaigns, kpi_entries, daily_reports, kpi_targets, kpi_metrics, users restart identity cascade`,
  );

  const metricRows = await db.insert(kpiMetrics).values(METRICS).returning();
  const metricId = new Map(metricRows.map((m) => [m.key, m.id]));

  const passwordHash = await bcrypt.hash("password123", 10);
  const userRows = await db
    .insert(users)
    .values(
      PEOPLE.map(({ factor: _f, ...p }) => ({
        ...p,
        advertiserLevel: p.role === "advertiser" ? (p.advertiserLevel ?? "junior") : null,
        passwordHash,
      })),
    )
    .returning();
  const supervisor = userRows.find((u) => u.role === "supervisor")!;
  const factorOf = new Map(PEOPLE.map((p) => [p.email, p.factor]));

  const now = new Date();
  const today = iso(now);
  const start = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const period = today.slice(0, 7);

  // Per-member target overrides for the running month
  const rizky = userRows.find((u) => u.email === "rizky@kpi.local")!;
  const bima = userRows.find((u) => u.email === "bima@kpi.local")!;
  await db.insert(kpiTargets).values([
    { userId: rizky.id, metricId: metricId.get("leads")!, period, target: 1_000 },
    { userId: rizky.id, metricId: metricId.get("revenue")!, period, target: 250_000_000 },
    { userId: bima.id, metricId: metricId.get("leads")!, period, target: 800 },
  ]);

  console.log("Generating daily reports…");
  const members = userRows.filter((u) => u.role !== "supervisor");
  const notReportedToday = new Set(["rizky@kpi.local", "bima@kpi.local", "yoga@kpi.local", "intan@kpi.local"]);
  const activityRows: (typeof activities.$inferInsert)[] = [];

  for (const u of members) {
    const role = u.role as Exclude<Role, "supervisor">;
    const f = factorOf.get(u.email)!;
    let keywords = Math.round(95 * f);
    for (let d = new Date(start); iso(d) <= today; d.setDate(d.getDate() + 1)) {
      const date = iso(d);
      const isSunday = d.getDay() === 0;
      if (isSunday) continue;
      if (date === today && notReportedToday.has(u.email)) continue;
      if (date !== today && rand() < 0.06 + (1 - f) * 0.12) continue; // occasionally missed

      const values = dailyValues(role, f);
      if (role === "seo") {
        keywords += Math.round((rand() - 0.35) * 3 * f);
        values.top10_keywords = keywords;
      }
      const ageDays = Math.round((now.getTime() - d.getTime()) / 86_400_000);
      const status = ageDays <= 1 ? "submitted" : rand() < 0.05 ? "revision" : ageDays <= 3 && rand() < 0.5 ? "submitted" : "approved";
      const createdAt = new Date(d);
      createdAt.setHours(16 + Math.floor(rand() * 3), Math.floor(rand() * 60));
      if (date === today) createdAt.setTime(now.getTime() - Math.floor(rand() * 3 * 3600_000) - 5 * 60_000);

      const [report] = await db
        .insert(dailyReports)
        .values({
          userId: u.id,
          date,
          summary: pick(SUMMARIES[role]),
          blockers: rand() < 0.2 ? "Waiting for new creative assets from design team." : null,
          planTomorrow: rand() < 0.7 ? "Continue optimization and prepare weekly report." : null,
          status,
          reviewerId: status === "submitted" ? null : supervisor.id,
          reviewNote: status === "revision" ? "Please double-check the revenue figure against the CRM." : null,
          reviewedAt: status === "submitted" ? null : new Date(createdAt.getTime() + 14 * 3600_000),
          createdAt,
          updatedAt: createdAt,
        })
        .returning();

      await db.insert(kpiEntries).values(
        Object.entries(values).map(([key, value]) => ({
          reportId: report!.id,
          userId: u.id,
          metricId: metricId.get(key)!,
          date,
          value,
        })),
      );

      if (ageDays <= 7) {
        activityRows.push({
          actorId: u.id,
          subjectUserId: u.id,
          type: "report_submitted",
          title: "Daily Report Submitted",
          description: `${u.name} submitted the report for ${new Date(date).toLocaleDateString("en-GB", { day: "2-digit", month: "short" })}`,
          href: `/reports/${report!.id}`,
          createdAt,
        });
        if (status !== "submitted") {
          activityRows.push({
            actorId: supervisor.id,
            subjectUserId: u.id,
            type: status === "approved" ? "report_approved" : "report_revision",
            title: status === "approved" ? "Report Approved" : "Revision Requested",
            description: `${u.name}'s report ${status === "approved" ? "approved" : "needs revision"}`,
            href: `/reports/${report!.id}`,
            createdAt: new Date(createdAt.getTime() + 14 * 3600_000),
          });
        }
      }
    }
  }

  console.log("Campaigns & tasks…");
  const adv = (email: string) => userRows.find((u) => u.email === email)!.id;
  const monthAgo = iso(new Date(now.getFullYear(), now.getMonth() - 1, 3));
  const campaignRows = await db
    .insert(campaigns)
    .values([
      { name: "Promo Gajian — Conversion", platform: "meta", objective: "Sales", product: "Skincare Bundle", dailyBudget: 750_000, status: "active", ownerId: adv("rizky@kpi.local"), startDate: monthAgo, landingPageUrl: "https://example.com/promo-gajian" },
      { name: "Retargeting 30D Engagers", platform: "meta", objective: "Leads", product: "Serum Brightening", dailyBudget: 350_000, status: "active", ownerId: adv("rizky@kpi.local"), startDate: monthAgo },
      { name: "Search — Brand Keywords", platform: "google", objective: "Sales", product: "All Products", dailyBudget: 400_000, status: "active", ownerId: adv("dewi@kpi.local"), startDate: monthAgo },
      { name: "Performance Max — Catalog", platform: "google", objective: "Sales", product: "Catalog", dailyBudget: 600_000, status: "active", ownerId: adv("dewi@kpi.local"), startDate: monthAgo },
      { name: "Spark Ads — Creator Review", platform: "tiktok", objective: "Leads", product: "Body Lotion", dailyBudget: 500_000, status: "paused", ownerId: adv("bima@kpi.local"), startDate: monthAgo, notes: "Paused: CPL above 80k for 3 days." },
      { name: "TikTok Live Boost", platform: "tiktok", objective: "Traffic", product: "Flash Sale", dailyBudget: 300_000, status: "draft", ownerId: adv("bima@kpi.local") },
      { name: "Shopee Ads — Keyword Bidding", platform: "shopee", objective: "Sales", product: "Skincare Bundle", dailyBudget: 250_000, status: "active", ownerId: adv("salsa@kpi.local"), startDate: monthAgo },
      { name: "Ramadan Early Bird", platform: "meta", objective: "Leads", product: "Hampers", dailyBudget: 500_000, status: "ended", ownerId: adv("salsa@kpi.local"), startDate: iso(new Date(now.getFullYear(), now.getMonth() - 1, 1)), endDate: iso(new Date(now.getFullYear(), now.getMonth() - 1, 28)) },
    ])
    .returning();

  const due = (n: number) => iso(new Date(now.getFullYear(), now.getMonth(), now.getDate() + n));
  const id = (email: string) => userRows.find((u) => u.email === email)!.id;
  await db.insert(tasks).values([
    { title: "Build landing page for Promo Gajian", category: "landing_page", assigneeId: id("fajar@kpi.local"), createdById: id("rizky@kpi.local"), campaignId: campaignRows[0]!.id, priority: "high", status: "in_progress", dueDate: due(1) },
    { title: "Fix pixel purchase event on checkout", category: "tracking", assigneeId: id("intan@kpi.local"), createdById: supervisor.id, priority: "urgent", status: "todo", dueDate: due(0) },
    { title: "Improve mobile PageSpeed for /serum", category: "site_performance", assigneeId: id("fajar@kpi.local"), createdById: supervisor.id, priority: "medium", status: "review", dueDate: due(3) },
    { title: "Prepare 6 new UGC creatives", category: "creative_brief", assigneeId: id("bima@kpi.local"), createdById: supervisor.id, campaignId: campaignRows[4]!.id, priority: "high", status: "todo", dueDate: due(2) },
    { title: "Weekly budget reallocation report", category: "ads_report", assigneeId: id("dewi@kpi.local"), createdById: supervisor.id, priority: "medium", status: "in_progress", dueDate: due(1) },
    { title: "Write pillar article: skincare routine", category: "article", assigneeId: id("nadia@kpi.local"), createdById: supervisor.id, priority: "medium", status: "done", dueDate: due(-2), completedAt: new Date(now.getTime() - 2 * 86_400_000) },
    { title: "Backlink outreach — beauty blogs", category: "backlink", assigneeId: id("yoga@kpi.local"), createdById: supervisor.id, priority: "high", status: "todo", dueDate: due(-1) },
    { title: "Set up Shopee ads keyword negatives", category: "campaign_optimization", assigneeId: id("salsa@kpi.local"), createdById: supervisor.id, campaignId: campaignRows[6]!.id, priority: "low", status: "done", dueDate: due(-3), completedAt: new Date(now.getTime() - 3 * 86_400_000) },
    { title: "Audit tracking parameters (UTM) all campaigns", category: "ads_report", assigneeId: id("rizky@kpi.local"), createdById: supervisor.id, priority: "medium", status: "todo", dueDate: due(4) },
    // Senior → junior (mentoring) waiting for the senior's approval, and a junior's request to the web master.
    { title: "Rapikan struktur campaign TikTok sesuai feedback", category: "campaign_optimization", description: "- [x] Pisah ad group per angle\n- [x] Matikan audiens CPA > 2x target\n- [ ] Tambah 3 creative baru", assigneeId: id("bima@kpi.local"), createdById: id("rizky@kpi.local"), priority: "high", status: "review", dueDate: due(1) },
    { title: "Sesi review mingguan campaign Bima & Salsa", category: "mentoring", assigneeId: id("rizky@kpi.local"), createdById: id("rizky@kpi.local"), priority: "medium", status: "todo", dueDate: due(2) },
    { title: "Landing page Shopee Flash Sale", category: "landing_page", assigneeId: id("intan@kpi.local"), createdById: id("salsa@kpi.local"), priority: "medium", status: "todo", dueDate: due(5) },
    { title: "Content brief: 10 articles for next month", category: "keyword_research", assigneeId: id("nadia@kpi.local"), createdById: supervisor.id, priority: "low", status: "in_progress", dueDate: due(6) },
  ]);

  const minutesAgo = (m: number) => new Date(now.getTime() - m * 60_000);
  activityRows.push(
    { actorId: id("rizky@kpi.local"), subjectUserId: id("fajar@kpi.local"), type: "task_created", title: "Task Assigned", description: "Rizky Pratama → Fajar Nugroho: Build landing page for Promo Gajian", href: "/tasks", createdAt: minutesAgo(35) },
    { actorId: supervisor.id, subjectUserId: id("intan@kpi.local"), type: "task_created", title: "Urgent Task", description: "Fix pixel purchase event on checkout", href: "/tasks", createdAt: minutesAgo(80) },
    { actorId: id("bima@kpi.local"), subjectUserId: id("bima@kpi.local"), type: "campaign_updated", title: "Campaign Paused", description: "Spark Ads — Creator Review paused (CPL above target)", href: "/campaigns", createdAt: minutesAgo(140) },
    { actorId: supervisor.id, subjectUserId: rizky.id, type: "target_updated", title: "KPI Target Updated", description: "Leads target for Rizky Pratama set to 1,000", href: "/targets", createdAt: minutesAgo(26 * 60) },
  );
  await db.insert(activities).values(activityRows);

  // A finished appraisal for a senior advertiser, scored like the sample HRGA form.
  const sampleScores = [
    [5, 4, 4, 3, 3],
    [4, 3, 3, 3, 3],
    [4, 3, 3, 3, 4],
    [4, 4, 4, 4, 4],
    [2, 2, 3, 3, 3],
    [3, 3, 4, 4, 3],
  ];
  const skillScores = Object.fromEntries(SKILL_ASPECTS.flatMap((a, ai) => a.indicators.map((ind, ii) => [ind.id, sampleScores[ai]![ii]!])));
  const kpi = {
    leads: { target: 1_000, real: 930, score: null },
    cpl: { target: 25_000, real: 27_500, score: null },
    quality: { target: 60, real: 51, score: null },
    budget: { target: null, real: null, score: 85 },
  };
  const result = computeAppraisal(skillScores, kpi);
  const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  await db.insert(performanceAppraisals).values({
    userId: rizky.id,
    reviewerId: supervisor.id,
    periodStart: iso(lastMonth),
    periodEnd: iso(new Date(now.getFullYear(), now.getMonth(), 0)),
    status: "final",
    skillScores,
    skillNote: "Kuat di problem solving. Perlu lebih aktif membimbing advertiser junior.",
    kpi,
    kpiNote: "CPL sedikit di atas target; fokus perbaikan kualitas lead bersama tim sales.",
    skillScore: result.skillTotal,
    kpiScore: result.kpiTotal,
    finalizedAt: now,
  });

  const [{ n }] = (await db.execute(sql`select count(*)::int as n from daily_reports`)).rows as { n: number }[];
  console.log(`Done: ${userRows.length} users, ${n} reports.`);
  console.log("Login with supervisor@kpi.local / password123 (all demo users share this password).");
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
