"use client";
import { useActionState,useEffect } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { updateLeadAction } from "@/actions/order-forms";
import { LEAD_STATUSES,LEAD_STATUS_LABEL } from "@/lib/order-form-input";
import { PAYMENT_STATUSES, PAYMENT_LABEL } from "@/lib/order-form-config";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
export function LeadEditor({lead,csos,canAssign}:{lead:{id:number;status:string;notes:string;assigneeId:number;paymentStatus:string;revenue:number;followUpStep:number;followUpAt:string};csos:{id:number;name:string}[];canAssign:boolean}){
 const [state,action,pending]=useActionState(updateLeadAction,undefined);const router=useRouter();
 useEffect(()=>{if(state?.ok){toast.success(state.message);router.refresh();}},[state,router]);
 return <form action={action} className="grid gap-3 p-4"><input type="hidden" name="id" value={lead.id} /><Label htmlFor="lead-status">Status</Label><select id="lead-status" name="status" defaultValue={lead.status} className="h-10 rounded-md border bg-background px-3 text-sm">{LEAD_STATUSES.map(s=><option key={s} value={s}>{LEAD_STATUS_LABEL[s]}</option>)}</select>{canAssign&&<><Label htmlFor="lead-cso">CSO penanganan</Label><select id="lead-cso" name="assigneeId" className="h-10 rounded-md border bg-background px-3 text-sm" defaultValue={lead.assigneeId}>{!csos.some(c=>c.id===lead.assigneeId)&&<option value={lead.assigneeId}>Pertahankan CSO saat ini</option>}{csos.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><p className="text-xs text-muted-foreground">Pemindahan mengubah akses penanganan; advertiser asal tetap. Percakapan WhatsApp yang sudah dibuka tidak berpindah otomatis.</p></>}<div className="grid gap-3 border-t pt-4 sm:grid-cols-2"><label className="grid gap-2 text-sm">Pembayaran<select name="paymentStatus" defaultValue={lead.paymentStatus} className="h-10 rounded-md border bg-background px-3 text-sm">{PAYMENT_STATUSES.map(s=><option key={s} value={s}>{PAYMENT_LABEL[s]}</option>)}</select></label><label className="grid gap-2 text-sm">Nilai order (Rp)<Input name="revenue" type="number" min={0} max={1000000000000} step={1} defaultValue={lead.revenue} required /></label><label className="grid gap-2 text-sm">Tahap follow-up<select name="followUpStep" defaultValue={lead.followUpStep} className="h-10 rounded-md border bg-background px-3 text-sm">{[0,1,2,3,4].map(step=><option key={step} value={step}>{step===0?"Belum follow-up":`Follow-up ${step}`}</option>)}</select></label><label className="grid gap-2 text-sm">Jadwal berikutnya (WIB)<Input name="followUpAt" type="datetime-local" defaultValue={lead.followUpAt} /></label></div><p className="text-xs text-muted-foreground">Pencatatan internal; perubahan pembayaran tidak mengirim event Purchase atau mengubah jumlah lead KPI.</p><Label htmlFor="lead-notes">Catatan follow-up</Label><textarea id="lead-notes" name="notes" maxLength={4000} defaultValue={lead.notes} className="min-h-36 rounded-lg border bg-background p-3 text-sm" placeholder="Hasil percakapan, kebutuhan customer, tindak lanjut…" />{state?.error&&<p role="alert" className="text-sm text-destructive">{state.error}</p>}<Button disabled={pending}>{pending?"Menyimpan…":"Simpan tindak lanjut"}</Button></form>;
}
