import Link from "next/link";
import { notFound } from "next/navigation";
import { and, desc, eq } from "drizzle-orm";
import { db } from "@/db";
import { orderLeadEvents, orderLeads, users } from "@/db/schema";
import { requireRole } from "@/lib/auth";
import { PageHeader, Panel } from "@/components/dashboard/panel";
import { Button } from "@/components/ui/button";
import { PAYMENT_LABEL, type LeadCommerce } from "@/lib/order-form-config";
import { LeadEditor } from "./lead-editor";
export default async function LeadPage({params}:{params:Promise<{id:string}>}){
 const actor=await requireRole("supervisor","advertiser","cso");const id=Number((await params).id);if(!Number.isSafeInteger(id))notFound();
 const [lead]=await db.select().from(orderLeads).where(and(eq(orderLeads.id,id),actor.role==="supervisor"?undefined:actor.role==="cso"?eq(orderLeads.assigneeId,actor.id):eq(orderLeads.ownerId,actor.id)));
 if(!lead)notFound();
 const csos=actor.role==="cso"?[]:await db.select({id:users.id,name:users.name}).from(users).where(and(eq(users.role,"cso"),eq(users.isActive,true)));
 const [owner]=await db.select({name:users.name}).from(users).where(eq(users.id,lead.ownerId));
 const [assigned]=await db.select({name:users.name}).from(users).where(eq(users.id,lead.assigneeId));
 const events=await db.select({id:orderLeadEvents.id,detail:orderLeadEvents.detail,createdAt:orderLeadEvents.createdAt,actor:users.name}).from(orderLeadEvents).innerJoin(users,eq(users.id,orderLeadEvents.actorId)).where(eq(orderLeadEvents.leadId,id)).orderBy(desc(orderLeadEvents.createdAt)).limit(30);
 return <><Link href="/leads" className="mb-3 inline-block text-sm text-muted-foreground hover:underline">← Kembali ke Leads</Link><PageHeader title={lead.name||"Customer tanpa nama"} description={`${lead.product} · ${lead.platform} · ${lead.date} WIB`} /><div className="grid items-start gap-4 lg:grid-cols-2"><div className="grid gap-4"><Panel title="Data customer"><dl className="grid grid-cols-2 gap-4 p-4 text-sm">{[["Nama",lead.name],["No. HP",lead.phone],["Email",lead.email],["Kota",lead.city],["Advertiser",owner.name],["CSO",assigned.name],["Sumber",lead.platform],["Referensi",lead.publicId]].map(([k,v])=><div key={k}><dt className="text-xs text-muted-foreground">{k}</dt><dd className="mt-1 break-all">{v||"—"}</dd></div>)}</dl><div className="flex gap-2 border-t p-4">{lead.phone&&<Button asChild size="sm"><a href={`https://wa.me/${lead.phone}`} target="_blank" rel="noreferrer">Hubungi customer</a></Button>}{lead.email&&<Button asChild variant="outline" size="sm"><a href={`mailto:${lead.email}`}>Email customer</a></Button>}</div></Panel><Panel title="Sumber kunjungan"><dl className="grid gap-2 p-4 text-sm">{Object.entries(lead.attribution).map(([k,v])=><div key={k}><dt className="text-xs text-muted-foreground">{k}</dt><dd className="break-all">{v}</dd></div>)}{!Object.keys(lead.attribution).length&&<p className="text-muted-foreground">Tidak ada parameter UTM atau ID klik.</p>}</dl></Panel></div><div className="grid gap-4"><Panel title="Tindak lanjut"><LeadEditor lead={{id:lead.id,status:lead.status,notes:lead.notes,assigneeId:lead.assigneeId,paymentStatus:lead.paymentStatus,revenue:lead.revenue,followUpStep:lead.followUpStep,followUpAt:lead.followUpAt?new Date(lead.followUpAt.getTime()+7*3600000).toISOString().slice(0,16):""}} csos={csos} canAssign={actor.role!=="cso"} /></Panel><Panel title="Riwayat penanganan"><div className="divide-y">{events.map(e=>{let info:{statusBefore?:string;statusAfter?:string;notes?:string;assigneeBefore?:number;assigneeAfter?:number;commerceAfter?:LeadCommerce}={};try{info=JSON.parse(e.detail);}catch{}return <div key={e.id} className="space-y-1 p-4 text-sm"><p className="font-medium">{e.actor}</p><p className="text-xs text-muted-foreground">{e.createdAt.toLocaleString("id-ID",{timeZone:"Asia/Jakarta"})} WIB · {info.statusBefore} → {info.statusAfter}</p>{info.assigneeBefore!==info.assigneeAfter&&<p className="text-xs">CSO #{info.assigneeBefore} → #{info.assigneeAfter}</p>}<p className="whitespace-pre-wrap">{info.notes}</p>{info.commerceAfter&&<p className="text-xs text-muted-foreground">{PAYMENT_LABEL[info.commerceAfter.paymentStatus]} · Rp {info.commerceAfter.revenue.toLocaleString("id-ID")} · Follow-up {info.commerceAfter.followUpStep}{info.commerceAfter.followUpAt?` · ${new Date(info.commerceAfter.followUpAt).toLocaleString("id-ID",{timeZone:"Asia/Jakarta"})} WIB`:""}</p>}</div>;})}{!events.length&&<p className="p-4 text-sm text-muted-foreground">Belum ada pembaruan penanganan.</p>}</div></Panel></div></div></>;
}
